package my_tasks.euler;

/**
 * RUS:
 * Последовательность треугольных чисел образуется путем сложения натуральных чисел. К примеру, 7-ое треугольное число равно 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. Первые десять треугольных чисел:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Перечислим делители первых семи треугольных чисел:
 *  1: 1
 *  3: 1, 3
 *  6: 1, 2, 3, 6
 * 10: 1, 2, 5, 10
 * 15: 1, 3, 5, 15
 * 21: 1, 3, 7, 21
 * 28: 1, 2, 4, 7, 14, 28
 * Как мы видим, 28 - первое треугольное число, у которого более пяти делителей.
 * Каково первое треугольное число, у которого более пятисот делителей?
 * ------------------------------------------------------------------
 *
 * ENG:
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 * ...
 * ...
 * We can see that 28 is the first triangle number to have over five divisors.
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * @author Volodymyr Burtsev at 16.03.2019 20:35
 */
public class Euler12 {

    /*
    Solution works but tooOoo long
     */
    public static void main(String[] args) {
        long triNum = 1;
        int seq = 1;
        int count = 1;
        int[] divs = new int[5000];
        divs[0] = 1;

        // Calculating
        while (count < 500) {
            triNum += ++seq;
            count = 1;
            for ( int i = 1; i * 2 <= triNum; i++) {
                if (triNum % i == 0) {
                    divs[count] = i;
                    count++;
                }
            }
        }

        // Show result
        System.out.print(triNum + " ::");
        int i = 1;
        for (; i < count; i++) {
            System.out.printf("\t" + divs[i]);
            if (i % 10 == 0) System.out.println("  [" + i + "]");
        }
        System.out.println("\t" + triNum + "  [" + i + "]");

    }

}